/* EDIT THIS FILE to add or change categories, products, collections, and articles. */
window.siteContent = {
  categories: [
    { name: "Home", icon: "⌂", color: "clay", description: "Cozy, clever upgrades" },
    { name: "Lifestyle", icon: "✦", color: "sage", description: "Everyday favorites" },
    { name: "Seasonal", icon: "☼", color: "gold", description: "Right-now inspiration" },
    { name: "Dorm & Apartment", icon: "□", color: "blue", description: "Small-space wins" },
    { name: "Beauty & Wellness", icon: "◌", color: "rose", description: "Feel-good essentials" },
    { name: "Tech & Gadgets", icon: "⌁", color: "charcoal", description: "Useful, not gimmicky" },
    { name: "Kitchen", icon: "♨", color: "gold", description: "Prep, cook, and sip smarter" }
  ],
  products: [
    { title: "Candle Warmer Lamp with Timer and Dimmer", category: "Home", price: "Cozy home pick", badge: "TRENDING", color: "sand", symbol: "☼", link: "https://amzn.to/4g9LLpO" },
    { title: "Bedsure Sherpa Fleece Throw Blanket", category: "Home", price: "Reader favorite", badge: "COZY FIND", color: "cream", symbol: "≈", link: "https://amzn.to/4gkCKcb" },
    { title: "YIHONG Woven Storage Basket Set", category: "Home", price: "Organization pick", badge: "SMART STORAGE", color: "oat", symbol: "▦", link: "https://amzn.to/46bpz8J" },
    { title: "Govee RGBIC Smart Table Lamp", category: "Home", price: "Ambient upgrade", badge: "VIRAL", color: "blue", symbol: "✦", link: "https://amzn.to/4xTd79D" },
    { title: "Mkono Ceramic Vase Set", category: "Home", price: "Editor pick", badge: "HOME DETAIL", color: "terracotta", symbol: "◌", link: "https://amzn.to/3SI6bgA" },
    { title: "Stanley Quencher H2.0 FlowState Tumbler", category: "Lifestyle", price: "Daily essential", badge: "MOST LOVED", color: "rose", symbol: "↗", link: "https://amzn.to/4wDQVze" },
    { title: "Owala FreeSip Insulated Water Bottle", category: "Lifestyle", price: "On-the-go pick", badge: "POPULAR", color: "sage", symbol: "⌁", link: "https://amzn.to/4quwmDR" },
    { title: "BAGSMART Travel Toiletry Bag", category: "Lifestyle", price: "Travel favorite", badge: "SMART FIND", color: "sand", symbol: "▦", link: "https://amzn.to/4zuRHRC" },
    { title: "Hatch Restore Sound Machine & Sunrise Alarm", category: "Lifestyle", categories: ["Lifestyle", "Beauty & Wellness", "Tech & Gadgets"], price: "Morning upgrade", badge: "WELLNESS", color: "oat", symbol: "☼", link: "https://amzn.to/4qsp3fP" },
    { title: "Clever Fox Premium Weekly Planner", category: "Lifestyle", price: "Get organized", badge: "EDITOR PICK", color: "olive", symbol: "✓", link: "https://amzn.to/4qx1JxQ" },
    { title: "MIULEE Burnt-Orange Corduroy Pillow Covers", category: "Seasonal", categories: ["Seasonal", "Home", "Dorm & Apartment"], price: "Fall refresh", badge: "FALL FAVORITE", color: "terracotta", symbol: "⌂", link: "https://amzn.to/3UKOwFx" },
    { title: "Bedsure Burnt-Orange Knit Throw Blanket", category: "Seasonal", categories: ["Seasonal", "Home", "Dorm & Apartment"], price: "Cozy seasonal pick", badge: "MOST SAVED", color: "sand", symbol: "≈", link: "https://amzn.to/3Slsc4v" },
    { title: "Yankee Candle Autumn Wreath Large Jar Candle", category: "Seasonal", price: "Classic fall scent", badge: "SEASONAL", color: "gold", symbol: "☼", link: "https://amzn.to/4cRfnWF" },
    { title: "Winemana Eucalyptus & Fall Leaf Garland", category: "Seasonal", price: "Easy decor update", badge: "FALL DECOR", color: "olive", symbol: "⌁", link: "https://amzn.to/4xdPlFq" },
    { title: "FEXIA Boho Fall Table Runner", category: "Seasonal", price: "Tabletop favorite", badge: "HOSTING PICK", color: "oat", symbol: "≈", link: "https://amzn.to/4gIU6Rm" },
    { title: "Pipishell Three-Tier Rolling Utility Cart", category: "Dorm & Apartment", price: "Small-space hero", badge: "DORM ESSENTIAL", color: "sage", symbol: "▦", link: "https://amzn.to/4xMdBhG" },
    { title: "Dormify Bedside Caddy", category: "Dorm & Apartment", price: "Bedside organizer", badge: "SPACE SAVER", color: "blue", symbol: "□", link: "https://amzn.to/4ielSq8" },
    { title: "Lifewit Large Laundry Hamper", category: "Dorm & Apartment", price: "Everyday essential", badge: "PRACTICAL PICK", color: "cream", symbol: "⌂", link: "https://amzn.to/46bKpVs" },
    { title: "Amazon Basics Velvet Nonslip Hangers", category: "Dorm & Apartment", price: "Closet upgrade", badge: "BEST VALUE", color: "rose", symbol: "⌁", link: "https://amzn.to/4qvhaqj" },
    { title: "Power Strip with USB & Extension Cord", category: "Dorm & Apartment", categories: ["Dorm & Apartment", "Tech & Gadgets", "Home"], price: "Room essential", badge: "MUST HAVE", color: "sand", symbol: "⚡", link: "https://amzn.to/45zhryK" },
    { title: "Kitsch Satin Heatless Curling Set", category: "Beauty & Wellness", price: "Overnight favorite", badge: "VIRAL BEAUTY", color: "rose", symbol: "≈", link: "https://amzn.to/4zv0naP" },
    { title: "LATME Ice Roller for Face and Eyes", category: "Beauty & Wellness", price: "Morning refresh", badge: "SELF-CARE", color: "blue", symbol: "◌", link: "https://amzn.to/45En4M1" },
    { title: "Tree Hut Tropic Glow Shea Sugar Scrub", category: "Beauty & Wellness", price: "Glow favorite", badge: "MOST LOVED", color: "gold", symbol: "✦", link: "https://amzn.to/4gjW6hE" },
    { title: "Sol de Janeiro Brazilian Bum Bum Cream", category: "Beauty & Wellness", price: "Cult favorite", badge: "TRENDING", color: "terracotta", symbol: "☼", link: "https://amzn.to/4ikiXMD" },
    { title: "e.l.f. Halo Glow Liquid Filter", category: "Beauty & Wellness", price: "Beauty editor pick", badge: "VIRAL", color: "sand", symbol: "✦", link: "https://amzn.to/3SFIV2K" },
    { title: "Anker 3-in-1 Cube with MagSafe", category: "Tech & Gadgets", price: "Charging upgrade", badge: "SMART TECH", color: "oat", symbol: "⚡", link: "https://amzn.to/4cTY1Zh" },
    { title: "JBL Go 4 Portable Bluetooth Speaker", category: "Tech & Gadgets", price: "Portable favorite", badge: "TOP RATED", color: "blue", symbol: "♪", link: "https://amzn.to/3SOtc1n" },
    { title: "Lamicall Gooseneck Phone Holder", category: "Tech & Gadgets", price: "Hands-free helper", badge: "USEFUL FIND", color: "sage", symbol: "⌁", link: "https://amzn.to/45HSscz" },
    { title: "Rocketbook Core Reusable Smart Notebook", category: "Tech & Gadgets", price: "Study essential", badge: "EDITOR PICK", color: "cream", symbol: "□", link: "https://amzn.to/4gr7Zm4" },
    { title: "Govee RGBIC LED Strip Lights", category: "Tech & Gadgets", price: "Room upgrade", badge: "VIRAL TECH", color: "olive", symbol: "✦", link: "https://amzn.to/4ikwYtG" },
    { title: "Fullstar Pro Original Vegetable Chopper & Spiralizer", category: "Kitchen", categories: ["Kitchen", "Home", "Lifestyle"], price: "Meal-prep helper", badge: "VIRAL KITCHEN", color: "sage", symbol: "▦", link: "https://amzn.to/4c3BJnz" },
    { title: "DASH Rapid Egg Cooker", category: "Kitchen", price: "Breakfast shortcut", badge: "MOST LOVED", color: "blue", symbol: "◌", link: "https://amzn.to/4cUizkn" },
    { title: "KitchenAid All-Purpose Kitchen Shears with Protective Sheath", category: "Kitchen", price: "Everyday essential", badge: "TOP RATED", color: "charcoal", symbol: "✂", link: "https://amzn.to/4gJpEXe" },
    { title: "Zulay Kitchen Powerful Handheld Milk Frother", category: "Kitchen", categories: ["Kitchen", "Lifestyle", "Home"], price: "Coffee-bar upgrade", badge: "COFFEE FAVORITE", color: "cream", symbol: "≈", link: "https://amzn.to/3S5tReG" },
    { title: "Alpha Grillers Instant-Read Digital Meat Thermometer", category: "Kitchen", price: "Cooking confidence", badge: "KITCHEN PICK", color: "terracotta", symbol: "↗", link: "https://amzn.to/3U7ipQo" },
    { title: "Easy-Pour Glass Oil Dispenser", category: "Kitchen", categories: ["Kitchen", "Home"], price: "Mess-free cooking helper", badge: "KITCHEN FIND", color: "gold", symbol: "↗", link: "https://amzn.to/4wGxm9u" },
    { title: "Magnetic Refrigerator Spice Rack", category: "Kitchen", categories: ["Kitchen", "Home"], price: "Counter-space saver", badge: "SMART STORAGE", color: "charcoal", symbol: "▦", link: "https://amzn.to/3SIjy0e" },
    { title: "Space-Saving Kitchen Strainer", category: "Kitchen", categories: ["Kitchen", "Home"], price: "Easy prep essential", badge: "USEFUL FIND", color: "sage", symbol: "◌", link: "https://amzn.to/4hNyODk" },
    { title: "Bekith 20-Pack Magnetic Spice Jars", category: "Kitchen", categories: ["Kitchen", "Home"], price: "Fridge organization upgrade", badge: "SMART STORAGE", color: "charcoal", symbol: "▦", link: "https://amzn.to/4zCM6sS" },
    { title: "Caraway 10.5-inch Non-Stick Ceramic Frying Pan", category: "Kitchen", categories: ["Kitchen", "Home"], price: "Everyday cookware pick", badge: "KITCHEN FAVORITE", color: "cream", symbol: "◌", link: "https://amzn.to/4zunUZk" },
    { title: "Kikcoin 3-Piece Ceramic Nonstick Frying Pan Set", category: "Kitchen", categories: ["Kitchen", "Home"], price: "Cookware set", badge: "3-PIECE SET", color: "oat", symbol: "◌", link: "https://amzn.to/4wEfYC7" },
    { title: "3-Piece Stainless Steel Colander Set", category: "Kitchen", categories: ["Kitchen", "Home"], price: "Prep and pasta essential", badge: "USEFUL FIND", color: "sage", symbol: "◌", link: "https://amzn.to/4gp4ywe" },
    { title: "4-Pack Fall Scented Soy Candle Set", category: "Seasonal", categories: ["Seasonal", "Home"], price: "Apple pie, cinnamon, harvest & wreath", badge: "FALL SCENTS", color: "terracotta", symbol: "☼", link: "https://amzn.to/4gJUnDI" },
    { title: "P&J Trading Spice Fragrance Oil Set", category: "Seasonal", categories: ["Seasonal", "Home", "Lifestyle"], price: "Cozy home fragrance set", badge: "FALL FAVORITE", color: "gold", symbol: "≈", link: "https://amzn.to/4gshX6G" },
    { title: "3500 Sq.Ft Smart HVAC Scent Diffuser", category: "Tech & Gadgets", categories: ["Tech & Gadgets", "Home"], price: "Whole-home fragrance upgrade", badge: "SMART HOME", color: "charcoal", symbol: "⌁", link: "https://amzn.to/3U1FpQK" },
    { title: "Pura Plus Smart Home Fragrance Diffuser", category: "Tech & Gadgets", categories: ["Tech & Gadgets", "Home", "Lifestyle"], price: "Smart scent for larger spaces", badge: "SMART HOME", color: "cream", symbol: "✦", link: "https://amzn.to/4zvYIBF" },
    { title: "200ML Ceramic Essential Oil Stone Diffuser", category: "Home", categories: ["Home", "Lifestyle", "Tech & Gadgets"], price: "Minimalist home fragrance", badge: "COZY HOME", color: "cream", symbol: "≈", link: "https://amzn.to/4c4kH8Y" },
    { title: "Large-Room Aroma Diffuser + 10 Essential Oils", category: "Home", categories: ["Home", "Lifestyle", "Tech & Gadgets"], price: "Ambient light & cool mist", badge: "AROMA SET", color: "oat", symbol: "✦", link: "https://amzn.to/3SRSuM5" },
    { title: "MacKenzie-Childs Courtly Check Large Enamel Canister", category: "Kitchen", categories: ["Kitchen", "Home", "Decorations"], price: "Statement countertop storage", badge: "DESIGNER FIND", color: "charcoal", symbol: "▦", link: "https://amzn.to/4wXk9JK" },
    { title: "Ninja® PossibleCooker™ PLUS 12-in-1, 8.5-qt, Black, MC1010", category: "Kitchen", categories: ["Kitchen", "Home", "Lifestyle"], price: "12-in-1 multicooker", badge: "KITCHEN POWERHOUSE", color: "charcoal", symbol: "♨", link: "https://amzn.to/4qIwS1k" }
  ],
  collections: [
    { title: "The Cozy Apartment List", subtitle: "Warm up your space without a full makeover", number: "01", color: "warm", slug: "cozy-apartment" },
    { title: "Dorm Room, Upgraded", subtitle: "Small-space essentials that earn their keep", number: "02", color: "cool", slug: "dorm-room-upgraded" },
    { title: "Actually Useful Viral Finds", subtitle: "The internet made us try them", number: "03", color: "green", slug: "actually-useful-viral-finds" }
  ],
  articles: [
    { title: "Fall Dorm Decor Ideas: 10 Cozy Small-Space Upgrades", tag: "DORM & APARTMENT", read: "7 min read", color: "gold", link: "blog/fall-dorm-decor-ideas-2026.html" },
    { title: "How to Build the Perfect Boo Basket 👻", tag: "HALLOWEEN", read: "5 min read", color: "terracotta", link: "blog/boo-basket-ideas-2026.html" },
    { title: "10 easy ways to make your apartment feel instantly cozier", tag: "HOME", read: "6 min read", color: "terracotta" },
    { title: "The small upgrades that make mornings feel less rushed", tag: "LIFESTYLE", read: "4 min read", color: "sage" },
    { title: "What we're saving this week: five finds under $40", tag: "THE WEEKLY FIVE", read: "3 min read", color: "gold" }
  ]
};

const productImages = [
  "https://wisehomeproducts.com/cdn/shop/files/6_750x.jpg?v=1705769242",
  "https://multimedia.bbycastatic.ca/multimedia/products/1500x1500/173/17399/17399223.jpeg",
  "https://i.ebayimg.com/images/g/BucAAeSwdvRpZo5c/s-l1200.webp",
  "https://static06.galaxus.com/productimages/7/9/2/0/1/2/9/6/5/5/0/6/1/9/2/6/7/4/4/92c3b150-8442-40b1-9f9c-37a6a9e5c09f.jpg_sea.jpeg",
  "https://www.oldbonesco.com/cdn/shop/files/0023799_68015_B.jpg?v=1752225209&width=1920",
  "https://soooq.com/cdn/shop/files/Web_PNG_Square-TheQuencherH2.OFlowState_Tumblerwithhandle20OZ-Indigo-Front_02cacf09-1dfd-43fd-8f6d-c470dc1c65d5.png?v=1737471012",
  "https://bakabukim.com/cdn/shop/files/S102a98232b9a4d3c9f417c2f81f971c5Z.webp?v=1743964050&width=1946",
  "https://www.instacart.com/image-server/1200x1200/www.instacart.com/assets/domains/product-image/file/large_33157c89-58cc-45ee-a10c-edc982e874b2.jpeg",
  "https://goodbuygear.com/cdn/shop/files/Shop-All-Default-Restore_ccc3b3f7-642d-48dd-af8a-cb8cfd5f5505_1_800x.jpg?v=1755547431",
  "https://cleverfoxplanner.com/cdn/shop/products/Main-Pearl_56ef05b9-1b90-4cf1-b448-9e6a02d1e60d_1400x.jpg?v=1698391744",
  "https://m.media-amazon.com/images/I/81XHB3Da%2BrL._AC_SL1500_.jpg",
  "https://i5.walmartimages.com/asr/a87e0d17-2778-4a4d-bfe1-b47790611436.ceb22a0df88cb7e1c8ab17c3118c8bc5.jpeg?odnBg=FFFFFF&odnHeight=768&odnWidth=768",
  "https://yankeecandle.imgix.net/b7433ad0-51cf-36da-9184-c3100cd69ce5/b7433ad0-51cf-36da-9184-c3100cd69ce5.jpg?auto=format%2Ccompress&h=2000&sort=1&w=2000",
  "https://assets.wfcdn.com/im/86169086/resize-h400-w400%5Ecompr-r85/3832/383211283/6FT%2BArtificial%2BFall%2BGarland%2C%2BFarmhouse%2BAutumn%2BEucalyptus%2BGarland%2BThanksgiving%2BDecor%2BFor%2BHome%2BFireplace%2BWedding%2BParty%2BArch%2BBackdrop%2BDoorways%2BTable%2BRunner%2BIndoor.jpg",
  "https://i5.walmartimages.com/asr/6eaf4e27-1f1a-41b1-9ab0-f031fa951c91.cabef7cb222b0f11cd2019e4a4ba48e6.jpeg?odnBg=FFFFFF&odnHeight=768&odnWidth=768",
  "https://m.media-amazon.com/images/I/61RAgsVBn1L.jpg",
  "https://m.media-amazon.com/images/I/81Ugw8CYj4L.jpg",
  "https://i5.walmartimages.com/seo/Lifewit-80L-Large-Tall-Laundry-Hamper-Collapsible-Laundry-Basket-Handles-Foldable-Clothes-Hampers-Laundry-Portable-Dirty-Clothes-Hamper-Dorm-College_c0f30cf8-710c-417b-8d10-b782219269fe.629b849134d8acc1e7ad98aec156508b.jpeg",
  "https://m.media-amazon.com/images/I/61OyJNbOHtL._AC_SL1500_.jpg",
  "https://i5.walmartimages.com/asr/4fe654e6-9900-49be-8a26-fe2e12b52525.7a7ebfba08f30282263b9a9e8aa82dea.jpeg?odnBg=FFFFFF&odnHeight=768&odnWidth=768",
  "https://www.becharmedgifts.com/cdn/shop/files/Kitsch_Satin_Heatless_Curling_Set_Sunset_Tie_Dye_Be_Charmed.jpg?v=1770154855",
  "https://m.media-amazon.com/images/I/311lx-q6jxL._SL500_.jpg",
  "https://digital.loblaws.ca/PCX/21656901_EA/en/1/7537130050_enfr_front_centre_marketing_1_GS1_Ecommerce_800.png",
  "https://images.beautybay.com/eoaaqxyywn6o/SOJA0018F_1.jpg_s3.lmb_i7mr8k/6e89f38f02d70d3f2da4cc6b56e78628/SOJA0018F_1.jpg",
  "https://media.glamourmagazine.co.uk/photos/6508666cfb876f3ae1706f7e/3%3A4/w_748%2Cc_limit/AMAZON%2520HIGHLIGHTERS%2520180923%2520%2520%2520180923%2520%2520%252061KYdU6aLqL._AC_SX679_.jpg",
  "https://rimage.ripley.com.pe/home.ripley/Attachment/MKP/3278/PMP20000428075/full_image-1.jpeg",
  "https://electroniquehifi.ca/cdn/shop/files/804952_1.jpg?v=1738968212",
  "https://i5.walmartimages.com/asr/fd802be9-f0fb-4df6-a935-6df4c6d75059.ec5b29e50c9354c1658a5d3c7f2a689b.jpeg?odnBg=FFFFFF&odnHeight=612&odnWidth=612",
  "https://m.media-amazon.com/images/I/81YJPnSHSCL._AC_SL1500_.jpg",
  "https://m.media-amazon.com/images/I/71QbUfYWa-L._AC_SL1500_.jpg",
  "https://m.media-amazon.com/images/I/81CWnvUBrrL._UF894%2C1000_QL80_.jpg",
  "https://cdn-tp6.mozu.com/24645-37138/cms/37138/files/5570a05e-1c79-4ed1-898d-f4f250e44edc",
  "https://medaidco.com/cdn/shop/files/61jQ2WhTA1L._AC_SL1500.jpg?v=1727362836",
  "https://cdn.shopify.com/s/files/1/0091/0593/2324/files/Milk_Frother_Without_Stand_-_Titanium_Silver.jpg?v=1774890464",
  "https://i5.walmartimages.com/seo/Alpha-Grillers-Meat-Thermometer-Digital-Instant-Read-Food-Thermometer-Cooking-Grilling-Air-Fryer-Griddle-Probe-Kitchen-Gadgets-Essentials-BBQ-Accesso_e6ca56b3-337f-49b5-bb6a-f5b4f910d2a1.9fec8ebdcb1b79155d7016a45e986fc9.jpeg",
  "https://www.shukanmall.com/product-img/Glass-Oil-Bottle-With-Ergonomi1-1678788678.jpg",
  "https://i.ebayimg.com/images/g/wX8AAOSwEqxnCUve/s-l1200.png",
  "https://slimages.macysassets.com/is/image/MCY/products/1/optimized/22801891_fpx.tif?fit=fit%2C1&hei=855&op_sharpen=1&wid=700",
  "https://i5.walmartimages.com/seo/20Pcs-Clear-Lid-Magnetic-Stainless-Steel-Spice-Jar-Sauce-Pepper-Seasoning-Storage-Container-Kitchen-Houseware_7ec3d79c-5e19-4932-a39a-e0b4e8113319.a84e9a06e9f0ad1d2d5f28d322361668.jpeg",
  "https://cdn.shopify.com/s/files/1/0606/8109/3269/files/c2c11c9f-7f10-4660-a131-3390b4702cf2.webp?v=1774907439",
  "https://img0.domopolis.ua/img.dp/01a/01a099a3f4cb58ebee168d4f6b91099dx700x700x80.jpg",
  "https://images.zola.com/ea8026fc-0678-4d4b-b039-28a2c929a7b9?fit=fill&h=640&w=640",
  "https://mobileimages.lowes.com/productimages/4f47bfbb-7d76-446b-9e91-0bdf50b8894d/77618433.jpeg?size=pdhz",
  "https://pandjtrading.com/cdn/shop/files/FR10SCS_MAIN.jpg",
  "https://www.nebuluxury.com/cdn/shop/files/hvac-beauty2_1200x1200.jpg?v=1756817564",
  "https://pura.com/cdn/shop/files/PuraPlus-PDP-EC2-V3.png?v=1727116299&width=1200",
  "https://multimedia.bbycastatic.ca/multimedia/products/500x500/185/18585/18585411.jpeg",
  "https://cdn.instant-upload.shop/cdn/1244/2024/0911/main-Ultimate-Aromatherapy-Diffuser-ampamp-Essential-Oil-Set-Ultrasonic-Top-10-Oils-Modern-with-4-Timer-7-Ambient-Light-Settings-Therapeutic-Grade-Lavender-1668909-501681.jpg",
  "https://i5.samsclubimages.com/asr/50a217a8-a801-4651-921c-7bb9e2fffa68.8d285ae71e9edf6d4a01860f204851f0.jpeg",
  "https://m.media-amazon.com/images/I/71dDSYSIQoL._AC_SL1500_.jpg"
];

window.siteContent.products.forEach((product, index) => {
  product.image = productImages[index];
});