const content = window.siteContent;
const categoryGrid = document.querySelector('#categoryGrid');
const productGrid = document.querySelector('#productGrid');
const collectionGrid = document.querySelector('#collectionGrid');
const articleGrid = document.querySelector('#articleGrid');
const slugify = value => value.toLowerCase().replace(/&/g, 'and').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const millisecondsPerWeek = 7 * 24 * 60 * 60 * 1000;
const homepageFeature = {
  titles: ["Light-Up Ceramic Ghost Decorations - 4 Pack", "Jabberin' Jack Talking Animated Pumpkin"],
  expiresAt: Date.parse("2026-08-24T06:00:00Z")
};
function weeklyRotation(items, filter) {
  if (items.length < 2) return items;
  const now = new Date();
  const mondayOffset = (now.getUTCDay() + 6) % 7;
  const monday = Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate() - mondayOffset);
  const weekNumber = Math.floor(monday / millisecondsPerWeek);
  const weeklyStep = filter === 'All' ? 5 : 1;
  const offset = (weekNumber * weeklyStep) % items.length;
  const rotated = [...items.slice(offset), ...items.slice(0, offset)];
  if (filter !== 'All' || now.getTime() >= homepageFeature.expiresAt) return rotated;
  const featured = homepageFeature.titles.map(title => rotated.find(item => item.title === title)).filter(Boolean);
  return [...featured, ...rotated.filter(item => !homepageFeature.titles.includes(item.title))];
}
function escapeXml(value = '') { return String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\"/g, '&quot;').replace(/'/g, '&apos;'); }
function wrapTitle(title, max = 24) { const words = String(title).split(/\s+/); const lines = []; let line = ''; words.forEach(word => { const next = line ? `${line} ${word}` : word; if (next.length > max && line) { lines.push(line); line = word; } else line = next; }); if (line) lines.push(line); return lines.slice(0, 4); }
function productFallback(title, category) { const lines = wrapTitle(title).map((line, index) => `<text x="50%" y="${250 + index * 44}" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-size="30" font-weight="700" fill="#3f352d">${escapeXml(line)}</text>`).join(''); const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="800" height="800" viewBox="0 0 800 800"><rect width="800" height="800" fill="#f3eee6"/><circle cx="400" cy="165" r="78" fill="#ded2c2"/><text x="400" y="187" text-anchor="middle" font-family="Georgia,serif" font-size="58" fill="#6f5c4b">✦</text>${lines}<text x="400" y="475" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-size="22" letter-spacing="3" fill="#8b755f">${escapeXml((category || 'THE FIND LIST').toUpperCase())}</text><line x1="250" y1="520" x2="550" y2="520" stroke="#cabba8" stroke-width="2"/><text x="400" y="575" text-anchor="middle" font-family="Georgia,serif" font-size="28" fill="#5b4a3d">THE FIND LIST</text><text x="400" y="615" text-anchor="middle" font-family="Arial,Helvetica,sans-serif" font-size="18" fill="#8b755f">Product image unavailable</text></svg>`; return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`; }
function applyImageFallbacks() { document.querySelectorAll('.product-photo').forEach(img => { const fallback = () => { if (img.dataset.fallbackApplied === 'true') return; img.dataset.fallbackApplied = 'true'; img.src = productFallback(img.dataset.title || img.alt, img.dataset.category || 'The Find List'); }; img.addEventListener('error', fallback, { once: true }); if (img.complete && img.naturalWidth === 0) fallback(); }); }
categoryGrid.innerHTML = content.categories.map(item => `<a class="category-card ${item.color}" href="#trending" data-category="${item.name}"><span class="category-icon">${item.icon}</span><span><strong>${item.name}</strong><small>${item.description}</small></span><b>→</b></a>`).join('');
function renderProducts(filter = 'All', expanded = false) { const filtered = filter === 'All' ? content.products : content.products.filter(product => { const productCategories = product.categories || [product.category]; return productCategories.includes(filter); }); const rotated = weeklyRotation(filtered, filter); const visible = expanded ? rotated : rotated.slice(0, 4); productGrid.innerHTML = visible.map((item, index) => `<article class="product-card"><a class="product-image ${item.color}" href="${item.link}" target="_blank" rel="sponsored nofollow noopener" aria-label="View ${item.title} on Amazon"><span class="product-badge">${item.badge}</span><img class="product-photo" src="${item.image}" alt="${item.title}" data-title="${item.title.replace(/\"/g, '&quot;')}" data-category="${item.category}" loading="lazy" decoding="async" /><button class="save-button" aria-label="Save ${item.title}" data-save="${index}">♡</button></a><p class="product-category">${item.category}</p><h3>${item.title}</h3><div class="product-meta"><span>${item.price}</span><a href="blog/${slugify(item.title)}.html">Read guide →</a></div></article>`).join(''); applyImageFallbacks(); document.querySelector('#loadMore').hidden = visible.length === rotated.length; }
renderProducts();
collectionGrid.innerHTML = content.collections.map(item => `<a class="collection-card ${item.color}" href="collections/${item.slug}.html"><span class="collection-number">${item.number}</span><div><p>THE FIND LIST</p><h3>${item.title}</h3><span>${item.subtitle}</span></div><b>Read the story →</b></a>`).join('');
articleGrid.innerHTML = content.articles.map(item => `<article class="article-card"><a href="blog/${item.slug}.html"><div class="article-image ${item.color}"><span>${item.tag}</span><div class="article-art">${item.art}</div></div><p>${item.tag}</p><h3>${item.title}</h3><span>Read guide →</span></a></article>`).join('');
document.querySelectorAll('.filter-pills button').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('.filter-pills button').forEach(btn => btn.classList.remove('active')); button.classList.add('active'); renderProducts(button.dataset.filter); document.querySelector('#loadMore').dataset.filter = button.dataset.filter; }));
document.querySelectorAll('[data-category]').forEach(card => card.addEventListener('click', () => { const filter = card.dataset.category; const button = [...document.querySelectorAll('.filter-pills button')].find(btn => btn.dataset.filter === filter); if (button) button.click(); }));
document.querySelector('#loadMore').addEventListener('click', event => renderProducts(event.currentTarget.dataset.filter || 'All', true));
document.querySelector('#productGrid').addEventListener('click', event => { const save = event.target.closest('.save-button'); if (!save) return; event.preventDefault(); save.textContent = save.textContent === '♡' ? '♥' : '♡'; save.classList.toggle('saved'); });
document.querySelector('.menu-toggle').addEventListener('click', event => { const nav = document.querySelector('.nav-links'); const open = nav.classList.toggle('open'); event.currentTarget.setAttribute('aria-expanded', String(open)); });
document.querySelector('.search-button').addEventListener('click', () => { const query = window.prompt('What are you looking for?'); if (!query) return; const match = content.products.find(item => item.title.toLowerCase().includes(query.toLowerCase()) || item.category.toLowerCase().includes(query.toLowerCase())); if (match) { document.querySelector('#trending').scrollIntoView({ behavior: 'smooth' }); renderProducts(match.category); } else window.alert(`No exact match for “${query}” yet. Try Home, Kitchen, Seasonal, Dorm, Beauty, or Tech.`); });
document.querySelector('#newsletterForm').addEventListener('submit', event => { event.preventDefault(); const form = event.currentTarget; const email = form.querySelector('#email').value.trim(); form.querySelector('.form-message').textContent = `You're on the list${email ? `, ${email}` : ''}. Watch your inbox for the next Find List.`; form.reset(); });
document.querySelector('#year').textContent = new Date().getFullYear();